name: E2E-test

on:
  schedule:
    - cron: "0 0 * * *"  
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to test'
        required: true
        default: 'production'

env: 
  TEST_ORG: org-workflow-test-organization 
  APP_ID_STAGING: 93678
  APP_ID_PRODUCTION: 93006
  
jobs:
  test-github-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.CI_TEST_TOKEN }}
          script: |
            const envMap = {
              production: ${{ env.APP_ID_PRODUCTION }},
              staging: ${{ env.APP_ID_STAGING }}
            }
            
            const default_env = 'production';
            const env = '${{ github.event.inputs.environment }}' || default_env;
            core.info(`Running e2e test for ${default_env} environment`);
            
            const app_id = envMap[env];
            const script = require(`${process.env.GITHUB_WORKSPACE}/.github/workflows/scripts/e2e-test.js`);
            
            await script(app_id, "${{ env.TEST_ORG }}", {github, core});
            await script(app_id, "${{ env.TEST_ORG }}", {github, core}, { repository: 'exclude-me', shouldRun: false });
            await script(app_id, "${{ env.TEST_ORG }}", {github, core}, { repository: 'wildcard-test', shouldRun: false });
